lesson-1-1
yasi44/react-todo pull request #1
Opened 2023-06-01 02:15 UTC by yasi44

pull request for lesson-1-1

2023-06-04 03:00 UTC, sinancengiz commented on src/App.js
> +  });
item.id should be used as key, and item text should only contain title. 

doc in the link has some examples for how to setting key in li element https://legacy.reactjs.org/docs/lists-and-keys.html

2023-06-04 03:01 UTC, sinancengiz requested changes
Great Job! only thing is that key needs to be set in li items , Please request another review when changes are done

2023-06-05 20:44 UTC, yasi44 reviewed
key added to <li> tag. pls review.

2023-06-05 23:21 UTC, sinancengiz approved these changes
LGTM! Great Job

2023-06-12 16:42 UTC, merged